version: '3'
services:
  nginx:
    image: nginx:latest
    ports:
      - 8080:80
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./server:/var/www
    depends_on:
      - php

  php:
    build: ./php
    ports:
      - 5173:5173
    volumes:
        - ./server:/var/www
    depends_on:
      - db

  mailhog:
      ports:
        - "1025:1025"
        - "8025:8025"
      image: mailhog/mailhog

  db:
    image: mysql:5.7
    container_name: db-host
    ports:
      - 13306:3306
    volumes:
      - ./mysql/data:/var/lib/mysql
    environment:
        MYSQL_DATABASE: laravel_db
        MYSQL_ROOT_PASSWORD: password

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:5
    ports:
      - 8888:80
    depends_on:
      - db
